---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
```

```{r, include = F}
data("rest_inspec")
rt_df = rest_inspec %>% 
  filter(grade %in% c("A","B","C")) %>% 
  mutate(cuisine_description = as.factor(cuisine_description))

rt_df %>% 
  group_by(cuisine_description) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n))

rt_clean = rt_df %>%
  mutate(cuisine_description = fct_recode(cuisine_description, Cafe = "Café/Coffee/Tea", 
                                          Latin = "Latin (Cuban, Dominican, Puerto Rican, South & Central American)")) %>% 
  filter(cuisine_description %in% c("American","Chinese","Pizza","Cafe","Italian",
                                    "Latin","Mexican","Japanese","Bakery","Caribbean")) %>% 
  mutate(cuisine_description = as.character(cuisine_description)) %>% 
  mutate(cuisine_description = factor(cuisine_description)) %>% 
  mutate(grade = as.character(grade), grade = factor(grade))
```



Column {data-width=650}
-----------------------------------------------------------------------

### Top 10 Cuisine(in number) vs. Score in MANHATTAN

```{r}
rt_clean %>%
  filter(boro == "MANHATTAN") %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>%
  plot_ly(y = ~ score, x = ~ cuisine_description, color = ~ cuisine_description,
          type = "box", colors = "viridis") %>% 
  layout(
    xaxis = list(title = "Top 10 Cuisine(in number)"),
    yaxis = list(title = "Score")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Grade of Chinese food restaurants in different areas in NY

```{r}
ch_grade = rt_clean %>% 
  filter(cuisine_description == "Chinese") %>%
  mutate(boro = factor(boro)) %>% 
  mutate(
    boro = fct_infreq(boro)) %>%
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()
ggplotly(ch_grade)
```

### Score vs. Grade.date

```{r}
rt_clean %>%
  mutate(text_label = str_c("Grade: ", grade, "\nResturants: ", dba)) %>%
  plot_ly(x = ~ grade_date, y = ~ score, color = ~ boro, text = ~ text_label,
    alpha = .5, type = "scatter", mode = "markers") %>% 
  layout(
    xaxis = list(title = "Grade Date"),
    yaxis = list(title = "Score")
  )
```

